### ISSUE TITLE
Imgui not compatible with Mac OS 10.11.4 and LibGDX 1.9.9

### ISSUE THREAD

**Issue by yuraj11** [kotlin-graphics/imgui#72] opened 2019-02-12 09:35 UTC
```
Exception in thread “main” com.badlogic.gdx.utils.GdxRuntimeException: java.lang.Exception: ERROR: 0:3: ‘’ :  version ‘150’ is not supported

    at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:117)
    at com.x.prototype.desktop.DesktopLauncher.main(DesktopLauncher.kt:21)
Caused by: java.lang.Exception: ERROR: 0:3: ‘’ :  version ‘150’ is not supported

    at gln.objects.GlShader$Companion.createFromSource-RHQEpZs(shader.kt:70)
    at imgui.impl.ImplGL3.createDeviceObjects(ImplGL3.kt:57)
    at imgui.impl.LwjglGlfw.newFrame(LwjglGlfw.kt:107)
```

**Comment by Sylvyrfysh** [comment] 2019-02-12 18:56
This is not an ImGui issue, per se. You are running an old mac which does not support OpenGL 3.2, which is the minimum version of OpenGL we support. An OpenGL 2 backend might be considered, but is a small use case for most of us. I'll see what I can do

**Comment by yuraj11** [comment] 2019-02-12 19:06
Hm how hard for one would be to make It compatible with opengl2? It is about changing this class https://github.com/kotlin-graphics/imgui/blob/master/src/main/kotlin/imgui/impl/ImplGL3.kt only?

**Comment by Sylvyrfysh** [comment] 2019-02-12 19:08
For me myself, this would be hard as my experience is with OpenGL 3 and 4, not 2. It would require making a separate class, ImplGL2, and only using functions up to OpenGL 2.1 in it, and changing the shaders to be OpenGL 2.1 compatible. If you wish to do it, please send a PR when it gets close to workable and I'll see what I can do to help.

**Comment by Sylvyrfysh** [comment] 2019-02-12 22:16
I'm gonna give this an attempt in the ImplGL2 branch. We'll see what comes of it

**Comment by Sylvyrfysh** [comment] 2019-02-13 02:29
OpenGL2 support is live in the ImplGL2 branch. Give it a shot and see if it works for you.

**Comment by yuraj11** [comment] 2019-02-13 07:54
Thanks for your effort!
So I have changed It like this:
```
LwjglGlfw.init(
GlfwWindow.from((Gdx.graphics as Lwjgl3Graphics).window.windowHandle),
clientApi_ = LwjglGlfw.GlfwClientApi.OpenGL2
)
```
`ImplGL3.renderDrawData(this)` => `LwjglGlfw.instance.renderDrawData(this)`
And It shows up this error: 
```java.lang.Exception: 0(11) : error C5060: out can't be used with non-varying uv
0(12) : error C5060: out can't be used with non-varying color
 ```

**Comment by elect86** [comment] 2019-02-13 09:40
[It looks](https://github.com/ocornut/imgui/blob/master/examples/imgui_impl_opengl2.cpp) like we shouldn't even use shader at all for GL2

**Comment by alex-dorokhov** [comment] 2019-02-13 12:13
I've also tried the latest version from ImplGL2 (with libgdx 1.9.8 though) and got this stacktrace: 
```
java.lang.Exception: ERROR: 0:7: Invalid storage qualifiers 'in' in global variable context
ERROR: 0:8: Invalid storage qualifiers 'in' in global variable context
ERROR: 0:9: Invalid storage qualifiers 'in' in global variable context
ERROR: 0:11: Invalid storage qualifiers 'out' in global variable context
ERROR: 0:12: Invalid storage qualifiers 'out' in global variable context
ERROR: 0:16: Use of undeclared identifier 'uv'
ERROR: 0:16: Use of undeclared identifier 'UV'
ERROR: 0:17: Use of undeclared identifier 'color'
ERROR: 0:17: Use of undeclared identifier 'Color'
ERROR: 0:18: Use of undeclared identifier 'Position'

	at gln.objects.GlShader$Companion.createFromSource-RHQEpZs(shader.kt:70)
	at imgui.impl.ImplGL2.createDeviceObjects(ImplGL2.kt:49)
	at imgui.impl.LwjglGlfw.newFrame(LwjglGlfw.kt:154)
	at imgui.impl.LwjglGlfw$Companion.newFrame(LwjglGlfw.kt:34)
```

**Comment by Sylvyrfysh** [comment] 2019-02-13 14:32
I know what I did wrong, will be fixed in an hour or two

**Comment by Sylvyrfysh** [comment] 2019-02-13 16:02
Should be fixed in ImmplGL2 commit 4b38958

**Comment by yuraj11** [comment] 2019-02-13 16:24
Ok now It works but there is still some issue when I resize window, does not happen on opengl3
![image](https://user-images.githubusercontent.com/5477518/52726766-1a195f80-2fb4-11e9-9f51-57a846ba4ae6.png)

**Comment by Sylvyrfysh** [comment] 2019-02-13 16:40
I cannot reproduce this issue. Is there something specific I need to do?

**Comment by elect86** [comment] 2019-02-13 16:42
ps: `ImGui.drawData?.run(LwjglGlfw.instance::renderDrawData)`

**Comment by yuraj11** [comment] 2019-02-13 16:53
@Sylvyrfysh Try `test lwjgl.kt` and change to `GlfwClientApi.OpenGL2` I am testing this on latest opengl version right now but this should be not a problem?

**Comment by yuraj11** [comment] 2019-02-13 16:55
![image](https://user-images.githubusercontent.com/5477518/52728931-7a120500-2fb8-11e9-8f5b-ae079a847a32.png)

**Comment by elect86** [comment] 2019-02-13 16:56
looks something wrong with the clearing, maybe it has something to do with the scissor?

**Comment by Sylvyrfysh** [comment] 2019-02-13 17:03
Retina mac?

**Comment by yuraj11** [comment] 2019-02-13 17:05
Right now I can not test it on Mac hardware. Currently I am using linux mint.

**Comment by Sylvyrfysh** [comment] 2019-02-13 17:07
Was able to reproduce after changing the window size. Looking into it

**Comment by yuraj11** [comment] 2019-02-13 17:08
Yes happens only when you resize the window :)

**Comment by Sylvyrfysh** [comment] 2019-02-13 17:57
0f9c3ab

**Comment by yuraj11** [comment] 2019-02-13 18:23
That one works correctly! :+1: I will try It on mac and let you know how It works there.

**Comment by yuraj11** [comment] 2019-02-13 18:55
Ok It also works on Mac. Thanks for your help! I appreciate It :+1:

**Comment by Sylvyrfysh** [comment] 2019-02-13 18:56
No problem!

**Comment by yuraj11** [comment] 2019-02-14 16:40
```
org.lwjgl.opengl.GL11C.nglDrawElements(IIIJ)V (0 bytes) @ 0x00000001155416c4 [0x0000000115541600+0xc4]
J 1294 C1 com.badlogic.gdx.backends.lwjgl3.Lwjgl3GL20.glDrawElements(IIILjava/nio/Buffer;)V (124 bytes) @ 0x0000000115538e94 [0x0000000115537880+0x1614]
J 1273 C1 com.badlogic.gdx.graphics.Mesh.render(Lcom/badlogic/gdx/graphics/glutils/ShaderProgram;IIIZ)V (257 bytes) @ 0x000000011552707c [0x00000001155269e0+0x69c]
J 1243 C1 com.badlogic.gdx.graphics.g2d.SpriteBatch.flush()V (193 bytes) @ 0x00000001155165ec [0x00000001155159c0+0xc2c]
J 2121 C1 com.badlogic.gdx.graphics.g2d.SpriteBatch.end()V (90 bytes) @ 0x000000011598a034 [0x0000000115989f20+0x114]
J 2592 C1 com.x.prototype.screen.editor.TileEditorScreen.renderScene(F)V (607 bytes) @ 0x0000000115e2578c [0x0000000115e1fe40+0x594c]
J 2715 C1 com.x.prototype.screen.base.BaseScreen.render(F)V (33 bytes) @ 0x0000000115fe137c [0x0000000115fe0c60+0x71c]
J 2711 C1 com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update()Z (213 bytes) @ 0x0000000115fdd1d4 [0x0000000115fdbfa0+0x1234]
j  com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop()V+101
j  com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lcom/badlogic/gdx/ApplicationListener;Lcom/badlogic/gdx/backends/lwjgl3/Lwjgl3ApplicationConfiguration;)V+257
```

**Comment by yuraj11** [comment] 2019-02-14 16:41
This error happens only on opengl2 when I try to render something libgdx related in my render method:
```
app.batch.begin()
app.batch.draw(app.assetManager.get<Texture>(path), 0f, 0f , 10f, 10f)
app.batch.end()
```

**Comment by Sylvyrfysh** [comment] 2019-02-14 17:27
Does your machine support opengl 4.3?

**Comment by yuraj11** [comment] 2019-02-14 17:30
I am testing this on OpenGL 4.6 and switched Imgui to OpenGL2 version but also happens on mac with open gl 2.1

**Comment by Sylvyrfysh** [comment] 2019-02-14 17:47
After your init, plug this code in:
`glEnable(GL43.GL_DEBUG_OUTPUT)
        glEnable(GL43.GL_DEBUG_OUTPUT_SYNCHRONOUS)

        cb = GLDebugCallback_43()
        glDebugMessageCallback(cb, 1)
        glDebugMessageControl(GL11.GL_DONT_CARE, GL11.GL_DONT_CARE, GL11.GL_DONT_CARE, BufferUtils.createIntBuffer(0),
                true)`

and add this class somewhere

`
class GLDebugCallback_43 : GLDebugMessageCallback() {

    override fun invoke(source: Int, type: Int, id: Int, severity: Int, len: Int, msg: Long, udata: Long) {
        if (id == 131185 || id == 131218)
        // || id == 131186
            return
        val _source: String = when (source) {
            GL_DEBUG_SOURCE_API -> "API"

            GL_DEBUG_SOURCE_WINDOW_SYSTEM -> "WINDOW SYSTEM"

            GL_DEBUG_SOURCE_SHADER_COMPILER -> "SHADER COMPILER"

            GL_DEBUG_SOURCE_THIRD_PARTY -> "THIRD PARTY"

            GL_DEBUG_SOURCE_APPLICATION -> "APPLICATION"

            GL_DEBUG_SOURCE_OTHER -> "UNKNOWN"
            else -> "UNKNOWN"
        }
        val _type: String
        val _severity: String = when (severity) {
            GL_DEBUG_SEVERITY_HIGH -> "HIGH"

            GL_DEBUG_SEVERITY_MEDIUM -> "MEDIUM"

            GL_DEBUG_SEVERITY_LOW -> "LOW"

            GL_DEBUG_SEVERITY_NOTIFICATION -> "NOTIFICATION"

            else -> "UNKNOWN"
        }

        when (type) {
            GL_DEBUG_TYPE_ERROR -> _type = "ERROR"

            GL_DEBUG_TYPE_DEPRECATED_BEHAVIOR -> _type = "DEPRECATED BEHAVIOR"

            GL_DEBUG_TYPE_UNDEFINED_BEHAVIOR -> _type = "UNDEFINED BEHAVIOR"

            GL_DEBUG_TYPE_PORTABILITY -> _type = "PORTABILITY"

            GL_DEBUG_TYPE_PERFORMANCE -> _type = "PERFORMANCE"

            GL_DEBUG_TYPE_OTHER -> _type = "OTHER"

            GL_DEBUG_TYPE_MARKER -> _type = "MARKER"

            else -> _type = "UNKNOWN"
        }

        println("ID $id: $_type of $_severity severity, raised from $_source: ${MemoryUtil.memASCII(msg)}")
        println("STACKTRACE:")
        Thread.currentThread().stackTrace.forEach(::println)
    }
}`

**Comment by yuraj11** [comment] 2019-02-14 17:59
[stacktrace.txt](https://github.com/kotlin-graphics/imgui/files/2866247/stacktrace.txt)
I have added but actually I am getting SIGSEGV

**Comment by Sylvyrfysh** [comment] 2019-02-14 18:03
From that stacktrace, ImGui is not doing anything to cause that. Did nothing get printed to console?

**Comment by yuraj11** [comment] 2019-02-14 18:05
```
new buffers sizes, vtx: 2048, idx: 1024
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x0000000041023e67, pid=3816, tid=0x00007f7e015a6700
#
```

**Comment by Sylvyrfysh** [comment] 2019-02-14 18:07
See if 48c582f fixes it

**Comment by yuraj11** [comment] 2019-02-14 18:15
It didn't help :-/

**Comment by elect86** [comment] 2019-02-14 18:21
If you comment out imgui calls, does it work fine?

**Comment by yuraj11** [comment] 2019-02-14 18:25
If I comment out everything from LwjglGlfw.newFrame(), ImGui.newFrame() to LwjglGlfw.instance.renderDrawData (and keep LwjglGlfw.init, context and all initialization) and draw something on screen using libgdx batch It works.

**Comment by elect86** [comment] 2019-02-14 18:27
What about only commenting out only `renderDrawData`?

**Comment by yuraj11** [comment] 2019-02-14 18:27
Same issue.

**Comment by yuraj11** [comment] 2019-02-14 18:28
And keep in mind this problem happens only with OpenGL2. On opengl3 It works without problems.

**Comment by elect86** [comment] 2019-02-14 18:35
I guess then the only way to find out is to comment out internally everything of `createDeviceObjects`, then uncomment step by step to find out the problematic call

**Comment by yuraj11** [comment] 2019-02-14 19:18
[guitest.zip](https://github.com/kotlin-graphics/imgui/files/2866496/guitest.zip)
I can easily simulate It with this demo.

**Comment by yuraj11** [comment] 2019-02-14 19:19
[guitest.zip](https://github.com/kotlin-graphics/imgui/files/2866499/guitest.zip)
I can easily simulate It with this demo.

**Comment by elect86** [comment] 2019-02-14 23:12
btw, thanks for your donation, appreciated!

**Comment by Sylvyrfysh** [comment] 2019-02-14 23:35
Tada! 2c1f58f

On a side note, I'll talk to the LibGDX guys about fixing stuff like that on their end too. Thanks for working with us through this

**Comment by yuraj11** [comment] 2019-02-15 09:19
Good this one works correctly! :+1:

**Comment by yuraj11** [comment] 2019-02-15 20:00
[hs_err_pid19901.log](https://github.com/kotlin-graphics/imgui/files/2870660/hs_err_pid19901.log)
There is still one issue but this one will be probably harder. It does happen on Mac with OpenGL2. It doesn't happen for me on Linux. It happens randomly or with some interaction in UI (and libgdx combination).

**Comment by Sylvyrfysh** [comment] 2019-02-15 20:12
This is a JVM bug specifically affecting Mac. [Find it here](https://bugs.openjdk.java.net/browse/JDK-8198881)

**Comment by yuraj11** [comment] 2019-02-15 20:23
Hm :thinking:  but this does not happen on other screens where we do not use ImGui.

**Comment by Sylvyrfysh** [comment] 2019-02-15 20:39
That's due to the compilation failing on getDrawData. I'll see if I can modify the code to fix it, but it's doubtful

**Comment by elect86** [comment] 2019-02-15 20:59
May trying another jdk be an option for you, @yuraj11? Like jdk11?

**Comment by Sylvyrfysh** [comment] 2019-02-15 21:03
Try d2c5266

**Comment by Sylvyrfysh** [comment] 2019-02-15 21:04
But I second elect's trying a different JDK

**Comment by yuraj11** [comment] 2019-02-15 21:12
Sorry I can not test It right now but I will check It tomorrow. I can also try with latest JDK after testing your change.

**Comment by yuraj11** [comment] 2019-02-16 15:32
[guitest.zip](https://github.com/kotlin-graphics/imgui/files/2872098/guitest.zip)
Something happened and I tried reverting your last change in ImplGL2 branch but does not help. I see you have rebased changes from master which probably contained some change which broke opengl2. You can check demo. It cointains latest implgl2 branch library. Somehow UI will dimiss after libgdx is drawing something. Didn't happen previously and there is no problem on opengl3.

**Comment by yuraj11** [comment] 2019-02-16 16:15
It is caused by this change https://github.com/kotlin-graphics/imgui/commit/5b5112c5d043abec2282180fd5cd98dc15a28067

**Comment by yuraj11** [comment] 2019-02-16 16:42
Beside the mentioned issue It looks that d2c5266 fixes the crash on Mac (will report If something changes).

**Comment by Sylvyrfysh** [comment] 2019-02-16 16:48
That is the change that fixes the memory leak. Try the latest changes, fixed again with a new memory eak workaround

**Comment by yuraj11** [comment] 2019-02-16 16:57
Now everything works good now.

**Comment by yuraj11** [comment] 2019-02-18 09:20
No issues with OpenGL2 on Mac so far :+1:

**Comment by yuraj11** [comment] 2019-02-18 12:10
[hs_err_pid5129.log](https://github.com/kotlin-graphics/imgui/files/2875491/hs_err_pid5129.log)
One more random crash on Mac (OpenGL2). Happens rarely comparing to previous issues.

**Comment by elect86** [comment] 2019-02-18 12:13
Weird, that belongs to stb though, so it should be outside our reaching area

An update to stb is coming to lwjgl though

**Comment by yuraj11** [comment] 2019-02-18 12:18
And I can not simulate It on linux on opengl2 or 3. So this could be again some mac issue (but I can not confirm for sure).

**Comment by yuraj11** [comment] 2019-02-19 08:13
[hs_err_pid12238.log](https://github.com/kotlin-graphics/imgui/files/2878992/hs_err_pid12238.log)
The last mentioned issue happens for me on OpenGL2 and Linux so It is not only mac specific but OpenGL2 in general.

**Comment by yuraj11** [comment] 2019-02-19 15:05
Now this last issue happened also on OpenGL3+.

**Comment by yuraj11** [comment] 2019-02-19 15:10
Ignore that last issue. It is probably on our side :man_facepalming: (I am calling multiple times LwjglGlfw.init, ImGui.addFont etc. in onShow method which is called when you come back from other screen but dispose is not called so that's why It happens only when you return from other screen) Anyway I think you can merge opengl2 branch to master. It is stable now.

**Comment by yuraj11** [comment] 2019-02-19 15:11
And thanks for your help again!

**Comment by elect86** [comment] 2019-02-19 15:36
Nice, ok then I'll merge later

Thank you, dear

**Closed by elect86** 2019-02-19 15:36 UTC

**Comment by yuraj11** [comment] 2019-02-19 18:09
[hs_err_pid2411.log](https://github.com/kotlin-graphics/imgui/files/2881359/hs_err_pid2411.log)
[hs_err_pid2428.log](https://github.com/kotlin-graphics/imgui/files/2881360/hs_err_pid2428.log)
I have found two random issues on Mac OpenGL2 :-/ The previous looks like fixed but this one happens on first time when opening the screen.
