### ISSUE TITLE
Keyboard not working (LWJGL)

### ISSUE THREAD

**Issue by mertcanekiz** [kotlin-graphics/imgui#104] opened 2019-10-12 15:47 UTC
I'm using existing LWJGL app and creating imgui like this:

```kotlin
ctx = Context()
val window = Application.instance.window.getHandle()
io.configFlags = io.configFlags or ConfigFlag.NavEnableKeyboard.i
io.configFlags = io.configFlags or ConfigFlag.NavEnableGamepad.i
ImGui.styleColorsDark()
implGlfw = ImplGlfw(GlfwWindow.from(window), true)
implGL3 = ImplGL3()
```

This works and I can see the demo window and open examples from the menu. However I cannot type in any input field.

I was using my own event system and installing my own callbacks to glfw and thought that might be the problem, so I commented out creation of key and char callbacks, but the result hasn't changed.

I also tried this with both 

```kotlin
implGlfw = ImplGlfw(GlfwWindow.from(window), true)
```

and 

```kotlin
implGlfw = ImplGlfw(GlfwWindow.from(window), false)
```

I am using lwjgl:3.2.2 and imgui:-SNAPSHOT on Windows 10 with JDK 11

**Comment by Sylvyrfysh** [comment] 2019-10-13 20:17
I will look deeper into this tomorrow, but first I'd recommend moving to the imgui tag `1.73-SNAPSHOT`. If that doesn't help, can you please post some basic code so we can see your render and set up loop? Thanks!

**Comment by mertcanekiz** [comment] 2019-10-14 19:47
Hi, the entire project is available [here](https://github.com/mertcanekiz/melkor), and the relevant files are
- [ImGuiLayer.kt](https://github.com/mertcanekiz/melkor/blob/master/src/main/kotlin/melkorkt/imgui/ImGuiLayer.kt) where I set up imgui,
- [Window.kt](https://github.com/mertcanekiz/melkor/blob/master/src/main/kotlin/melkorkt/core/Window.kt) where I set up GLFW window and callbacks, and
- [Application.kt](https://github.com/mertcanekiz/melkor/blob/master/src/main/kotlin/melkorkt/core/Application.kt) where the main loop happens.

Although the latest commit of this repo is still using `-SNAPSHOT`, moving to `1.73-SNAPSHOT` is still producing the same result on my machine.

**Comment by Sylvyrfysh** [comment] 2019-10-16 01:41
What I believe to be the issue is that your application is eating the inputs ImGui is expecting. ImGui uses different mouse inputs that you define, so it is able to get the mouse. However, the chars are eaten by your glfwSetKeyCallback. What you cold try doing is passing them to ImGui separately, after you have decided whether or not the rest of your app has consumed them.

**Comment by mertcanekiz** [comment] 2019-10-16 14:07
I've considered that, but like I mentioned in the first message, not installing my own key and char callbacks does not fix the problem.

How can I pass inputs to ImGui separately?

**Comment by elect86** [comment] 2019-10-25 10:49
Do you still experience this in 1.73?

**Comment by mertcanekiz** [comment] 2019-11-04 06:23
Yes this is still the case on version 1.73

**Comment by exuvo** [comment] 2019-11-25 19:15
I forward my inputs to Imgui via:
```
override fun keyTyped(character: Char): Boolean {
  if (ctx.io.wantCaptureKeyboard) {
    ctx.setCurrent() // Only needed if you use multiple context like I do
    ImplGlfw.charCallback(character.toInt())
    return true
  }
  return false;
}
```

I have similar calls to ImplGlfw.keyCallback(keycode, 0, GLFW.GLFW_RELEASE/GLFW_PRESS, 0); for keyUp and keyDown .

Too see if mouseclicks/scroll should be eaten by imgui or not i check ctx.io.wantCaptureMouse .

Scrolling:
```
if (ctx.io.wantCaptureMouse) {
  ctx.setCurrent()
  ImplGlfw.scrollCallback(Vec2d(0, -amount))
  return true
}
```

I hope that helps.

**Comment by elect86** [comment] 2019-12-11 09:07
I cant reproduce, I'd need a sscce (your link is a C project?)

**Comment by mertcanekiz** [comment] 2019-12-11 11:55
Sorry, the project was renamed, I updated the link.

**Comment by elect86** [comment] 2020-09-17 08:43
hi @mertcanekiz news?

**Closed** 2021-04-13 23:28 UTC
