### ISSUE TITLE
ImGui throwing exception when creating font's texture atlast

### ISSUE THREAD

**Issue by MrManiacc** [kotlin-graphics/imgui#87] opened 2019-05-03 22:37 UTC
So i'm getting the exception " OpenGL Error (GL_INVALID_OPERATION) at createFontsTexture" It's coming from the "lwjglGlfw.newFrame();" call. I think this may have something todo with the way i'm loading textures? Anyway, i've attached the exception image, an image of how I load textures, and an image of where the exception is coming from. 
![Image1](https://user-images.githubusercontent.com/4280960/57169004-682f4980-6dd2-11e9-919d-d77b877c02cd.PNG)
![image3](https://user-images.githubusercontent.com/4280960/57169005-682f4980-6dd2-11e9-876d-72c2502b9029.PNG)
![image2](https://user-images.githubusercontent.com/4280960/57169006-682f4980-6dd2-11e9-8f45-d44fe615886f.PNG)

**Comment by Sylvyrfysh** [comment] 2019-05-03 23:43
Before calling newFrame, could you do a call to checkError yourself? Your code may be throwing the error, but you do not check for it. If not, this [may] be a regression caused by 707e4bb as that was quick and hacky. If you can  confirm that there is no error before newFrame i'll come out with a new patch

**Comment by Sylvyrfysh** [comment] 2019-06-09 04:58
Hi! There hasn't been activity here in a month, if there is nothing more, please close this. In a week, this will be assumed resolved.

**Closed** 2019-06-16 04:56 UTC
Labels: unconfirmed
